name: Test & Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "fixtures/**"
      - "package.json"
      - "yarn.lock"

env:
  REGISTRY: ghcr.io
jobs:
  quality:
    runs-on: ubuntu-22.04
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        shell: bash
        run: |
          yarn install --immutable

  build:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [quality]
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: ./.github/actions/docker-build
        with:
          registry: ${{ env.REGISTRY }}
          image_name: "${{ github.repository }}/mediator"
          context: ./
          dockerfile: "Dockerfile"
          docker_user: ${{ github.actor }}
          docker_password: ${{ secrets.GITHUB_TOKEN }}
